import { useRouter } from 'next/router';
import Head from 'next/head';
import arr from './api/data';
import { useEffect, useState } from 'react';

const Detail = () => {
  const [id, setId] = useState('');
  const [data, setData] = useState('');
  const router = useRouter();
  useEffect(() => {
    if (router.isReady) {
      setId(router.query.id);
      const data = arr.filter((ar) => ar.id === parseInt(id));
      if (data.length) {
        setData(data[0]);
      } else {
        setData('file tidak ditemukan');
      }
    }
  }, [router.isReady, router.query, id]);

  return (
    <>
      <Head>
        <title>Play {data.title || data}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-white text-center text-2xl"> {data.title || data}</h1>
    </>
  );
};

export default Detail;
