import Head from 'next/head';
import Cardcomp from '../components/cardcomp';
import arr from './api/data';

export default function Home() {
  return (
    <div>
      <Head>
        <title>RRI PlayBook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center mt-7 gap-10 flex-wrap w-full mx-auto">
        {arr.map((ar) => (
          <Cardcomp key={ar.id} thumbnail={ar.thumbnail} title={ar.title} id={ar.id} desc={ar.desc} />
        ))}
      </div>
    </div>
  );
}
